poll/urls.py
from django.urls import path 
from . import views

app_name  = 'poll'
urlpatterns = [
    path('', views.home, name = 'home'),

    path('<int:q_id>/vote/', views.vote, name = 'vote'),

    path('<int:q_id>/result/', views.result, name = 'result'),

    path('api/vote_data/<int:q_id>/', views.get_vote_data, name='get_vote_data'),
]

pollsapp/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import include, path


def hello(request):
    return HttpResponse('<h1>Hola ingeniero 👾 <h1>')

def multiply(request, num):
    html = ''
    for i in range (1, 11):
        html += f'<p>{num} * {i} = {i * num} </p>'
    return HttpResponse(html)

def home(request):
    return render(request, 'home.html')

urlpatterns = [
    path('', home, name='home'),
    path('poll/', include('poll.urls')),
    path('admin/', admin.site.urls),
    path('hello/', hello, name = 'hello' ),
    path('table/<int:num>/', multiply, name ='multiply')
]

poll/models.py
from django.db import models

# Create your models here.

class Question (models.Model):
    question_text = models.CharField(max_length= 150)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    choice_text = models.CharField(max_length= 100)
    question = models.ForeignKey(Question, on_delete= models.CASCADE)
    vote = models.IntegerField(default= 0)

    def __str__(self):
        return self.choice_text

poll/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Question, Choice
from django.http import JsonResponse


# Create your views here.

def get_vote_data(request, q_id):
    question = get_object_or_404(Question, pk=q_id)
    choices = [{'choice_text': choice.choice_text, 'vote_count': choice.vote} for choice in question.choice_set.all()]
    data = ({'labels': [choice['choice_text'] for choice in choices], 'data': [choice['vote_count'] for choice in choices]})
    return JsonResponse(data)

def home (request):
    questions = Question.objects.all()
    return render(request, 'poll/home.html', {
        "questions": questions
        }
    )

def vote (request, q_id):
    q = get_object_or_404(Question, pk=q_id)
    if request.method == "POST":
        try:
            choice_id = request.POST.get('choice')
            choice = q.choice_set.get(pk=choice_id)
            choice.vote += 1
            choice.save()
            return redirect('poll:result',  q_id=q_id) 
        except (KeyError, Choice.DoesNotExist):
            return render (request, 'poll/vote.html', {
                "question": q,
                "error_message": "Para votar debes una opción"
    })
    return render(request, 'poll/vote.html', {
    "question": q
})

def result (request, q_id):
    try:
        q = Question.objects.get(pk=q_id)
    except Question.DoesNotExist:
        return redirect('poll:home')
    return render(request, 'poll/result.html', {
        "question": q
    })
 

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title> Encuestas | {% block title %} {% endblock %}</title>
    
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}

{% block content %}
<h1>Bienvenido al inicio </h1>
<a href="{% url 'poll:home' %}">Ir a las preguntas</a>
{% endblock %}

templates/poll/home.html
{% extends 'base.html' %}
{% block title %} Encuestas {% endblock %}

{% block content %}
<h1>Encuestas</h1>

<ul>{% for q in questions %}
<li><a href="{% url 'poll:vote' q.id %}">{{ q  }}</a>
    <a href="{%url 'poll:result' q.id %}">Ver Resultados</a></li>
{% endfor %} 
</ul>

{% endblock %}

templates/poll/result.html
{% extends 'base.html' %}

{% block title %} Resultados {% endblock %}

{% block content %}
<h1> {{ question.question_text }}</h1>
<ul>
    {% for c in question.choice_set.all %}
    <li>{{ c.choice_text }} - {{ c.vote }} voto{{ c.vote|pluralize }}</li>
    {% endfor %}
</ul>

<div id="voteChart" style="width: 400px; height: 300px; margin-top: 20px;">
    <canvas id="chartCanvas"></canvas>
</div>

<hr>
<a href="{% url 'poll:home' %}"> Encuestas </a>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels"></script> {% comment %}este plugin muestra los datos dentro de la grafica {% endcomment %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        fetch("{% url 'poll:get_vote_data' q_id=question.id %}")
        .then(response => response.json())
        .then(data => {
            const ctx = document.getElementById('chartCanvas').getContext('2d');
            const voteChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: data.labels,
                    datasets: [{
                        data: data.data,
                        backgroundColor: [
                            'rgba(227, 130, 187)',
                            'rgba(113, 161, 227)',
                            'rgba(240, 242, 113)',
                            'rgba(113, 219, 242 ',
                            'rgba(211, 113, 242)',
                            'rgba(133, 146, 158)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    responsive: true,
                    plugins: {
                        legend: {
                            position: 'top',
                        },
                        title: {
                            display: true,
                            text: 'Resultados de la encuesta'
                        },
                        datalabels: {
                            formatter: (value) => {
                                return value;
                                },
                            color: '##000000',
                        }
                    }
                },
                plugins: [ChartDataLabels]
            });
        });
    });
</script>
{% endblock %}

templates/poll/vote.html
{% extends "base.html" %}
{% block  title %} Vota {% endblock %}

{% block content %}

<h1>{{ question.question_text }}</h1>
{% if error_message %}
<div class="alert">
    <p>{{ error_message}} </p>
</div>
{% endif %}
<ul>
    <h2> Elige bien </h2>
    <form method="post">
        {% csrf_token %}
        {% for c in question.choice_set.all %}
        <input 
        type="radio"
        name="choice"
        id="c_{{c.id}}"
        value="{{c.id}}"/> 
        <label for="c_{{c.id}}">{{ c.choice_text }}</label>
        {% endfor %}
        <input type="submit" value ="Votar">
    </form>
</ul>
{% endblock %}